apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx-container
          image: ebsenthil/test123:1  # Public NGINX image
          ports:
            - containerPort: 3000  # Updated to 3000
          command: ["/bin/sh", "-c"]  # Override NGINX default port to 3000
          args:
            - |
              echo 'server { listen 3000; location / { root /usr/share/nginx/html; } }' > /etc/nginx/conf.d/default.conf &&
              nginx -g 'daemon off;'
